- name: Hello World Sample
  hosts: all
  tasks:
    - name: Hello Message
      debug:
        msg: "Hello World!"

    - name: scret is here
      debug:
        msg: "{{ vault_credential.vault_password }}"
