- name: Hello World Sample
  hosts: all
  tasks:
    - include_vars: "vaulted.yml"
    
    - name: Hello Message
      debug:
        msg: "Hello World!"

    - name: scret is here
      debug:
        msg: "{{ test }}"
