---
#
# copy of https://github.com/mkanoor/playbook/blob/master/update_automate_workspace.yml
#
# Playbook to update attributes in the root object in automate workspace
# You can pass in extra vars to control the automate_workspace
- hosts: localhost
  vars:
    root_attrs: { 'name': 'Fred Flintstone', 'address': 'Bedrock' }
    state_attrs: { 'name': 'Wilma Flintstone', 'friend': 'Betty Rubble' }

  tasks:
    - name: Set the automate workspace url
      set_fact:
        aws_url: "{{ manageiq.api_url }}/api/{{ manageiq.automate_workspace }}"
        
    - name: Update the root object in the workspace
      uri:
        url: "{{ aws_url }}"
        method: POST
        body:
          action: edit
          resource: "{ 'objects': { 'root': {{ root_attrs }} }, 'state_vars': {{ state_attrs }}}"
        body_format: json
        validate_certs: False
        headers:
          X-Auth-Token: "{{ manageiq.api_token }}"
          Content-Type: "application/json" 
        status_code: 200
      register: output
      
    - name: "Artifact URL of test results to Tower Workflows"
      set_stats:
        data: 
          root_attrs: "{{ root_attrs }}"
          state_attrs: "{{ state_attrs }}"
          from_update_workspace: "{{ output }}"
