---
#
# Shows the value of all variables/facts.
#
# Example:
#
#   ansible-runner -p projects/vars_stats.yml -i vars_1 --cmdline "--extra-vars miq_data='from-command-line'" --debug  run /tmp/private
#
- hosts: localhost
  tasks:
    - name: "Artifact data of test results to next playbook"
      set_stats:
        data:
          miq_attrs: "something"
          ip_address: "1.2.3.4"
          service_template_provision_task__status: "Warn"
          service_template_provision_task__options__config_info__be__very__deep: true
          service_template_provision_task:options:config_info:be:very:deep2: true
          service_template_provision_task/options/config_info/be/very/deep3: true

    - debug: var=miq_data
    - debug: var=vars
