---
# vars.yml
#
# Shows the value of all variables/facts.
#
# Example:
#
#   ansible-playbook vars.yml -e 'hosts=localhost'
#
- hosts: all
  tasks:
    - debug: var=miq_test1
    - debug: var=vars
    - debug: var=hostvars[inventory_hostname]
